services:
  cmfcmf_media_module.collection_permission.container:
    class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\CollectionPermissionContainer

  cmfcmf_media_module.collection_permission.user:
    class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\UserCollectionPermission
    tags:
      - { name: cmfcmf_media_module.collection_permission }

  cmfcmf_media_module.collection_permission.group:
    class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\GroupCollectionPermission
    tags:
      - { name: cmfcmf_media_module.collection_permission }
