services:
  cmfcmf_media_module.collection_template.abstract_service:
    abstract: true
    arguments: [@templating]

  cmfcmf_media_module.collection_template.cards:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\CardsTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }

  cmfcmf_media_module.collection_template.slider:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\SliderTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }

  cmfcmf_media_module.collection_template.grid:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\GridTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }
