services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    cmfcmf_media_module.collection_permission.container:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\CollectionPermissionContainer

    cmfcmf_media_module.collection_permission.group:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\GroupCollectionPermission
        tags: ['cmfcmf_media_module.collection_permission']

    cmfcmf_media_module.collection_permission.owner:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\OwnerCollectionPermission
        tags: ['cmfcmf_media_module.collection_permission']

    cmfcmf_media_module.collection_permission.user:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\UserCollectionPermission
        tags: ['cmfcmf_media_module.collection_permission']
