services:
    cmfcmf_media_module.collection_permission.container:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\CollectionPermissionContainer

    cmfcmf_media_module.collection_permission.group:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\GroupCollectionPermission
        arguments:
            - '@translator'
            - '@zikula_users_module.current_user'
            - '@zikula_groups_module.group_repository'
        tags: ['cmfcmf_media_module.collection_permission']

    cmfcmf_media_module.collection_permission.owner:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\OwnerCollectionPermission
        arguments:
            - '@translator'
            - '@zikula_users_module.current_user'
        tags: ['cmfcmf_media_module.collection_permission']

    cmfcmf_media_module.collection_permission.user:
        class: Cmfcmf\Module\MediaModule\Security\CollectionPermission\UserCollectionPermission
        arguments:
            - '@translator'
            - '@zikula_users_module.current_user'
            - '@zikula_users_module.user_repository'
        tags: ['cmfcmf_media_module.collection_permission']
