services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Content types
    Cmfcmf\Module\MediaModule\ContentType\CollectionType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setCollectionRepository, ['@Cmfcmf\Module\MediaModule\Entity\Collection\Repository\CollectionRepository']]
            - [setSecurityManager, ['@cmfcmf_media_module.security_manager']]
            - [setSelectedTemplateFactory, ['@cmfcmf_media_module.collection_template.selected_factory']]
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]
        tags: ['zikula.content_type']
    Cmfcmf\Module\MediaModule\ContentType\Form\Type\CollectionType:
        parent: zikula.content_type.form.base
        arguments:
            $securityManager: '@cmfcmf_media_module.security_manager'
        tags: ['form.type']
    Cmfcmf\Module\MediaModule\ContentType\MediaType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setMediaRepository, ['@Cmfcmf\Module\MediaModule\Entity\Media\Repository\MediaRepository']]
            - [setSecurityManager, ['@cmfcmf_media_module.security_manager']]
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]
            - [setEnableMediaViewCounter, ['@Zikula\ExtensionsModule\Api\VariableApi']]
        tags: ['zikula.content_type']
    Cmfcmf\Module\MediaModule\ContentType\Form\Type\MediaType:
        parent: zikula.content_type.form.base
        arguments:
            $securityManager: '@cmfcmf_media_module.security_manager'
        tags: ['form.type']
