services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $securityManager: '@cmfcmf_media_module.security_manager'

    # Providers
    Cmfcmf\Module\MediaModule\HookProvider\CollectionUiHooksProvider:
        calls:
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]

    Cmfcmf\Module\MediaModule\HookProvider\MediaUiHooksProvider:
        calls:
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]

    Cmfcmf\Module\MediaModule\HookProvider\LicenseUiHooksProvider:
