services:
    # Providers
    cmfcmf_media_module.hook_provider.ui_hooks.base:
        abstract: true
        arguments:
            - '@translator'
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
            - '@twig'
            - '@cmfcmf_media_module.security_manager'

    cmfcmf_media_module.hook_provider.ui_hooks.collections:
        class: Cmfcmf\Module\MediaModule\HookProvider\CollectionUiHooksProvider
        parent: cmfcmf_media_module.hook_provider.ui_hooks.base
        calls:
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]

    cmfcmf_media_module.hook_provider.ui_hooks.media:
        class: Cmfcmf\Module\MediaModule\HookProvider\MediaUiHooksProvider
        parent: cmfcmf_media_module.hook_provider.ui_hooks.base
        calls:
            - [setMediaTypeCollection, ['@cmfcmf_media_module.media_type_collection']]

    cmfcmf_media_module.hook_provider.ui_hooks.licenses:
        class: Cmfcmf\Module\MediaModule\HookProvider\LicenseUiHooksProvider
        parent: cmfcmf_media_module.hook_provider.ui_hooks.base
