services:
  cmfcmf_media_module.importer_collection:
    class: Cmfcmf\Module\MediaModule\Importer\ImporterCollection

  cmfcmf_media_module.importer.abstract_service:
    abstract: true
    arguments: [@translator, @form.factory, @cmfcmf_media_module.media_type_collection, "@doctrine.orm.entity_manager", "@=service('kernel').getModule('CmfcmfMediaModule').getTranslationDomain()"]

  cmfcmf_media_module.importer.server_directory:
    parent: cmfcmf_media_module.importer.abstract_service
    class: Cmfcmf\Module\MediaModule\Importer\ServerDirectoryImporter
    calls:
      - [setUploadManager, [@stof_doctrine_extensions.uploadable.manager]]
    tags:
      - { name: 'cmfcmf_media_module.importer' }

  cmfcmf_media_module.importer.downloads_module:
    parent: cmfcmf_media_module.importer.abstract_service
    class: Cmfcmf\Module\MediaModule\Importer\DownloadsModuleImporter
    calls:
      - [setUploadManager, ["@stof_doctrine_extensions.uploadable.manager"]]
      - [setUserDataDirectory, ["%datadir%"]]
    tags:
      - { name: 'cmfcmf_media_module.importer' }

  cmfcmf_media_module.importer.very_simple_downloads_module:
    parent: cmfcmf_media_module.importer.abstract_service
    class: Cmfcmf\Module\MediaModule\Importer\VerySimpleDownloadsModuleImporter
    calls:
      - [setUploadManager, ["@stof_doctrine_extensions.uploadable.manager"]]
      - [setUserDataDirectory, ["%datadir%"]]
    tags:
      - { name: 'cmfcmf_media_module.importer' }
