services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Cmfcmf\Module\MediaModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    cmfcmf_media_module.media_type.abstract_media:
        abstract: true

    cmfcmf_media_module.media_type.abstract_file:
        parent: cmfcmf_media_module.media_type.abstract_media
        abstract: true
        calls:
            - [injectThings, ['@file_locator', '@liip_imagine.cache.manager', '%kernel.project_dir%']]

    cmfcmf_media_module.media_type.url:
        class: Cmfcmf\Module\MediaModule\MediaType\Url
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.deezer:
        class: Cmfcmf\Module\MediaModule\MediaType\Deezer
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.sound_cloud:
        class: Cmfcmf\Module\MediaModule\MediaType\SoundCloud
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.flickr:
        class: Cmfcmf\Module\MediaModule\MediaType\Flickr
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.you_tube:
        class: Cmfcmf\Module\MediaModule\MediaType\YouTube
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.twitter:
        class: Cmfcmf\Module\MediaModule\MediaType\Twitter
        parent: cmfcmf_media_module.media_type.abstract_media
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.image:
        class: Cmfcmf\Module\MediaModule\MediaType\Image
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.pdf:
        class: Cmfcmf\Module\MediaModule\MediaType\Pdf
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.plaintext:
        class: Cmfcmf\Module\MediaModule\MediaType\Plaintext
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.audio:
        class: Cmfcmf\Module\MediaModule\MediaType\Audio
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.video:
        class: Cmfcmf\Module\MediaModule\MediaType\Video
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.markdown:
        class: Cmfcmf\Module\MediaModule\MediaType\Markdown
        parent: cmfcmf_media_module.media_type.abstract_file
        calls:
            - [setMarkdownParser, ['@Michelf\MarkdownExtra']]
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.archive:
        class: Cmfcmf\Module\MediaModule\MediaType\Archive
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']

    cmfcmf_media_module.media_type.unknown:
        class: Cmfcmf\Module\MediaModule\MediaType\Unknown
        parent: cmfcmf_media_module.media_type.abstract_file
        tags: ['cmfcmf_media_module.media_type']
