imports:
  - { resource: 'collectiontemplates.yaml' }
  - { resource: 'hooks.yaml' }
  - { resource: 'contenttypes.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Cmfcmf\Module\MediaModule\CmfcmfMediaModule'
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.cache_dir%'
            $dataDirectory: '%datadir%'
            $fileLocator: '@file_locator'

    Cmfcmf\Module\MediaModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Cmfcmf\Module\MediaModule\Security\CollectionPermission\CollectionPermissionContainer:
        arguments:
            $permissions: !tagged_iterator cmfcmf_media_module.collection_permission

    # Imagine filter
    cmfcmf_media_module.filter.custom_image_filter:
        class: Cmfcmf\Module\MediaModule\Imagine\Filter\Loader\CustomImageFilter
        arguments:
            $imagine: '@liip_imagine'
            $fontCollection: '@Cmfcmf\Module\MediaModule\Font\FontCollection'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: cmfcmfmediamodule.custom_image_filter }

    Cmfcmf\Module\MediaModule\Importer\ImporterCollection:
        arguments:
            $importers: !tagged_iterator cmfcmf_media_module.importer
        lazy: true

    # Collection of media types
    Cmfcmf\Module\MediaModule\MediaType\MediaTypeCollection:
        arguments:
            $mediaTypes: !tagged_iterator cmfcmf_media_module.media_type
        lazy: true

    # Collection of "Collection" templates
    Cmfcmf\Module\MediaModule\CollectionTemplate\TemplateCollection:
        arguments:
            $templates: !tagged_iterator cmfcmf_media_module.collection_template
        lazy: true

    # Fonts
    Cmfcmf\Module\MediaModule\Font\FontCollection:
        arguments:
            $loaders: !tagged_iterator cmfcmf_media_module.font_loader
        lazy: true

    Cmfcmf\Module\MediaModule\Listener\EntityLifecycleListener:
        tags: ['doctrine.event_subscriber']

parameters:
    liip_imagine.cache.signer.class: Cmfcmf\Module\MediaModule\Imagine\Cache\DummySigner
