imports:
  - { resource: 'mediatypes.yaml' }
  - { resource: 'collectiontemplates.yaml' }
  - { resource: 'formtypes.yaml' }
  - { resource: 'hooks.yaml' }
  - { resource: 'importers.yaml' }
  - { resource: 'contenttypes.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Cmfcmf\Module\MediaModule\CmfcmfMediaModule'
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.cache_dir%'

    Cmfcmf\Module\MediaModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Cmfcmf\Module\MediaModule\Security\CollectionPermission\CollectionPermissionContainer:
        arguments:
            $permissions: !tagged_iterator cmfcmf_media_module.collection_permission

    # Imagine filter
    cmfcmf_media_module.filter.custom_image_filter:
        class: Cmfcmf\Module\MediaModule\Imagine\Filter\Loader\CustomImageFilter
        arguments:
            $imagine: '@liip_imagine'
            $fontCollection: '@Cmfcmf\Module\MediaModule\Font\FontCollection'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: cmfcmfmediamodule.custom_image_filter }

    # Collection of media types
    cmfcmf_media_module.media_type_collection:
        class: Cmfcmf\Module\MediaModule\MediaType\MediaTypeCollection
        lazy: true

    # Collection of "Collection" templates
    cmfcmf_media_module.collection_template_collection:
        class: Cmfcmf\Module\MediaModule\CollectionTemplate\TemplateCollection
        arguments:
            $templates: !tagged_iterator cmfcmf_media_module.collection_template
        lazy: true

    # Fonts
    cmfcmf_media_module.font.font_loader:
        class: Cmfcmf\Module\MediaModule\Font\FontLoader
        tags: ['cmfcmf_media_module.font']

parameters:
    liip_imagine.cache.signer.class: Cmfcmf\Module\MediaModule\Imagine\Cache\DummySigner
