services:
  # Security management
  cmfcmf_media_module.security_manager:
    class: Cmfcmf\Module\MediaModule\Security\SecurityManager

  # Module upgrader and version checker
  cmfcmf_media_module.upgrade.module_upgrader:
    class: Cmfcmf\Module\MediaModule\Upgrade\ModuleUpgrader
    arguments: [@translator, %kernel.cache_dir%, %kernel.root_dir%]

  cmfcmf_media_module.upgrade.version_checker:
    class: Cmfcmf\Module\MediaModule\Upgrade\VersionChecker
    arguments: [%kernel.cache_dir%]


  # Listeners
  cmfcmf_media_module.listener.module:
    class: Cmfcmf\Module\MediaModule\Listener\ModuleListener
    arguments: [@doctrine.entitymanager]
    tags:
      - { name: kernel.event_subscriber }

  cmfcmf_media_module.listener.thirdparty:
    class: Cmfcmf\Module\MediaModule\Listener\ThirdPartyListener
    arguments: [%kernel.root_dir%]
    tags:
      - { name: kernel.event_subscriber }

  # Link container
  cmfcmf_media_module.container.links:
    class: Cmfcmf\Module\MediaModule\Container\LinkContainer
    arguments: [@router, @cmfcmf_media_module.security_manager]
    tags:
      - { name: zikula.link_container }


  # Collection of media types
  cmfcmf_media_module.media_type_collection:
    class: Cmfcmf\Module\MediaModule\MediaType\MediaTypeCollection
    lazy: true


  # Collection of "Collection" templates
  cmfcmf_media_module.collection_template_collection:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\TemplateCollection
    lazy: true


  # Twig extension
  cmfcmf_media_module.twig_extension.description_escaping:
    class: Cmfcmf\Module\MediaModule\Twig\TwigExtension
    arguments: [@markdown_extra_parser, @hook_dispatcher, @cmfcmf_media_module.security_manager, @cmfcmf_media_module.upgrade.version_checker]
    public: false
    tags:
        - { name: twig.extension }


  # Hook handlers
  cmfcmf_media_module.hook_handler.base:
    abstract: true
    arguments: [@doctrine.entitymanager, @request_stack, @templating]

  cmfcmf_media_module.hook_handler.license:
    class: Cmfcmf\Module\MediaModule\HookHandler\LicenseHookHandler
    parent: cmfcmf_media_module.hook_handler.base

  cmfcmf_media_module.hook_handler.media:
    class: Cmfcmf\Module\MediaModule\HookHandler\MediaHookHandler
    parent: cmfcmf_media_module.hook_handler.base
    calls:
      - [setMediaTypeCollection, [@cmfcmf_media_module.media_type_collection]]

  cmfcmf_media_module.hook_handler.collection:
    class: Cmfcmf\Module\MediaModule\HookHandler\CollectionHookHandler
    parent: cmfcmf_media_module.hook_handler.base
    calls:
      - [setMediaTypeCollection, [@cmfcmf_media_module.media_type_collection]]


  # Collection templates
  cmfcmf_media_module.collection_template.abstract_service:
    abstract: true
    arguments: [@templating]

  cmfcmf_media_module.collection_template.cards:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\CardsTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }

  cmfcmf_media_module.collection_template.slider:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\SliderTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }

  cmfcmf_media_module.collection_template.grid:
    class: Cmfcmf\Module\MediaModule\CollectionTemplate\GridTemplate
    parent: cmfcmf_media_module.collection_template.abstract_service
    tags:
      - { name: cmfcmf_media_module.collection_template }


  # Media types
  cmfcmf_media_module.media_type.abstract_media:
    abstract: true
    arguments: [@templating]

  cmfcmf_media_module.media_type.abstract_file:
    parent: cmfcmf_media_module.media_type.abstract_media
    abstract: true
    calls:
      - [injectThings, [@service_container, @file_locator, %kernel.root_dir%]]

  cmfcmf_media_module.media_type.deezer:
    class: Cmfcmf\Module\MediaModule\MediaType\Deezer
    parent: cmfcmf_media_module.media_type.abstract_media
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.sound_cloud:
    class: Cmfcmf\Module\MediaModule\MediaType\SoundCloud
    parent: cmfcmf_media_module.media_type.abstract_media
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.flickr:
    class: Cmfcmf\Module\MediaModule\MediaType\Flickr
    parent: cmfcmf_media_module.media_type.abstract_media
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.you_tube:
    class: Cmfcmf\Module\MediaModule\MediaType\YouTube
    parent: cmfcmf_media_module.media_type.abstract_media
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.twitter:
    class: Cmfcmf\Module\MediaModule\MediaType\Twitter
    parent: cmfcmf_media_module.media_type.abstract_media
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.image:
    class: Cmfcmf\Module\MediaModule\MediaType\Image
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.pdf:
    class: Cmfcmf\Module\MediaModule\MediaType\Pdf
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.plaintext:
    class: Cmfcmf\Module\MediaModule\MediaType\Plaintext
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.audio:
    class: Cmfcmf\Module\MediaModule\MediaType\Audio
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.video:
    class: Cmfcmf\Module\MediaModule\MediaType\Video
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.markdown:
    class: Cmfcmf\Module\MediaModule\MediaType\Markdown
    parent: cmfcmf_media_module.media_type.abstract_file
    calls:
      - [setMarkdownParser, [@markdown_extra_parser]]
    tags:
      - { name: cmfcmf_media_module.media_type }

  cmfcmf_media_module.media_type.archive:
    class: Cmfcmf\Module\MediaModule\MediaType\Archive
    parent: cmfcmf_media_module.media_type.abstract_file
    tags:
      - { name: cmfcmf_media_module.media_type }

