preset: symfony

disabled:
  - multiline_array_trailing_comma
  - pre_increment
  - single_quote
  - concat_without_spaces
  - empty_return
  - spaces_cast 
  - unalign_equals
  - unalign_double_arrow
  - phpdoc_to_comment
  - phpdoc_annotation_without_dot
  
enabled:
  - short_array_syntax
