language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr MediaModule.zip .
    - wget https://github.com/zikula/core/releases/download/1.4.1/Zikula_Core-1.4.1.build128.tar.gz
    - tar -xpzf Zikula_Core-1.4.1.build128.tar.gz
    - rm Zikula_Core-1.4.1.build128.tar.gz
    - cd Zikula_Core-1.4.1
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir cmfcmf
    - cd cmfcmf
    - mkdir media-module
    - cd media-module
    - unzip -q ../../../../MediaModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'CmfcmfMediaModule', '3', 'Media Module', 'collections', '...', 'cmfcmf/media-module', '1.0.2', 'N;', '3', 'N;', '1.4.1', '1.4.99');"

script:
    - php app/console lint:yaml modules/cmfcmf/media-module/Resources
    - php app/console lint:twig @CmfcmfMediaModule
    - phpunit --configuration modules/cmfcmf/media-module/phpunit.xml.dist

before_deploy:
    - pwd
    - ls -lisa
    - composer install --no-dev
    - zip -qr MediaModule.zip .
    - rm -R .git

deploy:
  provider: releases
  api_key:
    secure: RPMBTvwkOnQUvJRd9MG9WgTtmJzJrScWQb9+d3shhjrh85XswSSbUMViJr7xYr8WHj1lNekd2E1maPDppdtHPltmdGDbKTar2xOf+7931UgYSkOzrOEJA7CEeO0GIt/n8Ay4nD8rWcx0UvEsl29vzlfitq0xzldyMInolIA1Pl/O+xxLJ0Gq1HLAOFrQuaANfrVF+oDhf87C1pcBq30nqiW9GxIAiBHIKkmJUJybnh8gB7hFVKQfU0G5SAkg2q9xXy6T89FTYPl4A7B79IC0uIoq9kgQrlBdJsLhv1iS0MJIsFnDTgterwdlhz+9hHFWoHfarJMbSz//L/3lwnAc5+0GI+WRAm2my7Q59cT+DPyJx9LUnq/ShNdP5xdKnzVo+mvwJNIbUKjw39jdRXpoPfWnWBRtn8qA3sxMhk+JEmgeRlAiskKESOlybIcKQZw06prJtsxLUy02Dt4mrNp8XguqiZ+QqjYgpQeNX89l9+LtVAYjcUEfRuovixrpCMRUZMnePZo/vcO6E6JaapDNHPi3dzb488WKVNE4sqUYalLok2ZLXN+kVfzDS8lyo/tp77Mu2ta2cWNtMYGKIcynrygG1dfmZvPAIJIT4kHMZsqc18h+FP+fyo2R+CEB+O8cO7BCInaFYQi0k2u8HTsFYIgKPlOvpHmTqhE/JVY3AHg=
  file: MediaModule.zip
  on:
    tags: true
    repo: cmfcmf/MediaModule
