language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr MediaModule.zip .
    - wget https://github.com/zikula/core/releases/download/1.4.1/Zikula_Core-1.4.1.build128.tar.gz
    - tar -xpzf Zikula_Core-1.4.1.build128.tar.gz
    - rm Zikula_Core-1.4.1.build128.tar.gz
    - cd Zikula_Core-1.4.1
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir cmfcmf
    - cd cmfcmf
    - mkdir media-module
    - cd media-module
    - unzip -q ../../../../MediaModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'CmfcmfMediaModule', '3', 'Media Module', 'collections', '...', 'cmfcmf/media-module', '1.0.2', 'N;', '3', 'N;', '1.4.1', '1.4.99');"

script:
    - php app/console lint:yaml modules/cmfcmf/media-module/Resources
    - php app/console lint:twig @CmfcmfMediaModule
    - phpunit --configuration modules/cmfcmf/media-module/phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_deploy:
    - cd ..
    - mkdir release
    - cd release
    - unzip -q ../MediaModule.zip
    - rm -Rf vendor
    - rm -Rf .git
    - composer install --no-dev --prefer-dist
    - zip -qr MediaModule.zip .

deploy:
  provider: releases
  api_key:
    secure: "TGMNRRxSJ0fivBRVW8IySmJNkxSc2G/84TVOvKKN6KMnv8TaaaQSYSzfB/CaTwALjG18PTrrw8AW12jlfc3dES+9Cwz5/2M7a59/jDdJdJXYCuE/B3h03u1t1abR6ygJBU2gThSk+jZtzE1tycuDF6xT1qS3hxVgMGNMjYa2oglBp/m/77RU66vkMg22JTtGTPfJxBmxJiIMjlJNgziJ5naJi1jKvcuFt/AW0C5uymwxUrhBTbnxoY4hhXkpzHZpG5XbSy3DyzkGc0VZ/0RgmwNITnS2xqc3xQKyFePNzY8PdmcjrZf1ADf4/yHyGmUKpogGKeXvHDoJDZGTmD3mfVrbmWVt8HdHdKhwQW+WKcyYpTZhNF2PvVp7lABAzxXPrx0bxGBo3PmbiJoCsb0pbAUgb9PWtHxLuxy7u4SeGXzoXB/hDfQc5xgZp10IUXlBs5gkL9A0Kiuq5+k7cp0qYKlIlmcF0JDi42MHGwvvJx8HH6bMSx6QHUlg+nUB2Ci5lMYE1+lwVpsCI9OeowBJWLc4JHXG+2qIL0JBW4RmxRR260AV484oscFpH2ndmsV1IgUjyh7boLa9BwK0AOxdfo5JfL8St8uPurvQXv99DprTS1uRY7+Bm92nw3waAilES5aqfQf3ger9VJqveYxYJ4g7J15r0LThfQs3Ol/FD4I="
  file: MediaModule.zip
  on:
    tags: true
    repo: cmfcmf/MediaModule
