language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr MediaModule.zip .
    - wget https://github.com/zikula/core/releases/download/1.4.3/Zikula_Core-1.4.3.build183.tar.gz
    - tar -xpzf Zikula_Core-1.4.3.build183.tar.gz
    - rm Zikula_Core-1.4.3.build183.tar.gz
    - cd Zikula_Core-1.4.3
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir cmfcmf
    - cd cmfcmf
    - mkdir media-module
    - cd media-module
    - unzip -q ../../../../MediaModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'CmfcmfMediaModule', '3', 'Media Module', 'media', '...', 'cmfcmf/media-module', '1.2.1', 'N;', '3', 'N;', '1.4.3', '1.4.99');"

script:
    - php app/console lint:yaml modules/cmfcmf/media-module/Resources
    - php app/console lint:twig @CmfcmfMediaModule
    - phpunit --configuration modules/cmfcmf/media-module/phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover -v

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_PHP_VERSION == "5.6" && ../deployment/deploy-master-to-github.sh

before_deploy:
    - cd ..
    - mkdir release
    - cd release
    - unzip -q ../MediaModule.zip
    - rm -Rf vendor
    - rm -Rf .git
    - composer install --no-dev --prefer-dist
    - rm auth.json
    - zip -qr MediaModule.zip .
    - cd ../Zikula_Core-1.4.3

deploy:
  - provider: releases
    api_key:
      secure: "LVvn+d8ULh08ctwn+VF+nD6mDf3vI1sDXAkTIzA8YNVwCNeR9oOLKBtMCDGeZ6bIn72BNYAn/o4UCkowfFHXE18XkXKYZUjbbXfMQJKxNLDM9gYRrHZNl+Ha9njY6ZmZCSczaRC5WqHsJfHFpbi8BrqQ0wLbk/xG0N089WLxx+jHvmH5sdZKPelrcgrTXsjMIwCGqJxDtfj8OTDOJVk8U3G7Rq9xfJHhnsEv10H9OBY+SIN1jfARnNQv5I6XkaBmWXSUfrIdReEKJOj7DB/Yp3SjuC+TElKv3gJwHawa/nBd4GV0SQUClQuc85RtSf69ZW31Yt4i43bdduICGgdlIMKKoiHzQiesTXEPjbcEvJKkaI+f/qQVyk8U3+G3Z6SMNHYn5M1j4KyAQMRWvovD+G8EVSLsf8wTtqnDP5VO0DoNO8q516IbdWMqwin6/nLpp5Ys3bsBQmUrw8uC7RZoTulevJpojWknntgv9D/SCHFjPN1L9p2kzDEbktqVLXqkpYFe4YkALLnuZq0BDdP2VtGUUXjngIERw//2LN+eNPQtANloeyq601fTyMn51HSy2cby8D6aI5v1rX+/tO8H1wl+rRWLfHkIKeUvfRzjIc8nR0TQLB5qXkA8oHyVEgeF+M0VQYVW5pBlt8PUk0i1AFzUXZ5LdCZVwyWK2DVuovQ="
    file: ../release/MediaModule.zip
    on:
      tags: true
      repo: cmfcmf/MediaModule
#  - provider: heroku
#    api_key:
#      secure: "VZI7VzLegExOf/xfYI9fw1gEnZNo6Sahh+kjmT0P+1jhbiiHS9DsmspCevy0KW7rXiZba/ih3jiMU9BzwtpEXfcxBfETjvVT8ekMeTgKokkOi2/HynM8Z4UaBKd9WJlLJVCUFZHIZkSsfvvfRS7e2P34IPseVpi7CBsGZ+oj5D6Et2rGY0HjAsSS3A4QI0xwTdoa6apjciHTjPuyaZkDieMoyeoRr0zteoU9jlfLnyooXdy1GTH+rBRRU0NH6eyjQ5G0DvqbYh8IF2A6GcdWs37n4DakrboMw+FbWtrDPoL23wrEpwr42bPaN+tRZkENCgxZXpCtTxS1usmjbBFoj/fxfr8uNEoU6AE9MYOfczwF4mShaI/Ub41HVcSNVBh7UP6Du8rJnYq2hAiFm4QhIVzi1M3BlU7qK+1ZhyDnXS70BLWkUeob0yOuv1G/Mvhy35PxvcXYuE4mL7jGDmOQGPDGSwZ1ZmBpI/0ERKzwOolY8eqwNol8CddJN3Tp31+z4UncTwrGpDhVe9Bz1mD4p/S4Qn4jRlgcEJxReSClpO1ZW/KL2D/hVZHbrh9VeAqp/ooRNuUnxAdcEL5Oda7Kqyt5wKTlfEqJGGyFNBnXom07MZCCZu9BA5hECJ8y7gzqtrbcUf9hIRHWhwyLrapXvmdrH0f+AsLXrX/AHmf7fKo="
#    app: mediamodule
#    on: 
#      branch: master
#      php: 5.6
#    run:
#      - ls
#      - pwd
#      - restart
#    skip_cleanup: true

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  
  
  
