language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr MediaModule.zip .
    - wget https://github.com/zikula/core/releases/download/1.4.1/Zikula_Core-1.4.1.build128.tar.gz
    - tar -xpzf Zikula_Core-1.4.1.build128.tar.gz
    - rm Zikula_Core-1.4.1.build128.tar.gz
    - cd Zikula_Core-1.4.1
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir cmfcmf
    - cd cmfcmf
    - mkdir media-module
    - cd media-module
    - unzip -q ../../../../MediaModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'CmfcmfMediaModule', '3', 'Media Module', 'collections', '...', 'cmfcmf/media-module', '1.1.0', 'N;', '3', 'N;', '1.4.1', '1.4.99');"

script:
    - php app/console lint:yaml modules/cmfcmf/media-module/Resources
    - php app/console lint:twig @CmfcmfMediaModule
    - phpunit --configuration modules/cmfcmf/media-module/phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_deploy:
    - cd ..
    - mkdir release
    - cd release
    - unzip -q ../MediaModule.zip
    - rm -Rf vendor
    - rm -Rf .git
    - composer install --no-dev --prefer-dist
    - rm auth.json
    - zip -qr MediaModule.zip .

deploy:
  provider: releases
  api_key:
    secure: "LVvn+d8ULh08ctwn+VF+nD6mDf3vI1sDXAkTIzA8YNVwCNeR9oOLKBtMCDGeZ6bIn72BNYAn/o4UCkowfFHXE18XkXKYZUjbbXfMQJKxNLDM9gYRrHZNl+Ha9njY6ZmZCSczaRC5WqHsJfHFpbi8BrqQ0wLbk/xG0N089WLxx+jHvmH5sdZKPelrcgrTXsjMIwCGqJxDtfj8OTDOJVk8U3G7Rq9xfJHhnsEv10H9OBY+SIN1jfARnNQv5I6XkaBmWXSUfrIdReEKJOj7DB/Yp3SjuC+TElKv3gJwHawa/nBd4GV0SQUClQuc85RtSf69ZW31Yt4i43bdduICGgdlIMKKoiHzQiesTXEPjbcEvJKkaI+f/qQVyk8U3+G3Z6SMNHYn5M1j4KyAQMRWvovD+G8EVSLsf8wTtqnDP5VO0DoNO8q516IbdWMqwin6/nLpp5Ys3bsBQmUrw8uC7RZoTulevJpojWknntgv9D/SCHFjPN1L9p2kzDEbktqVLXqkpYFe4YkALLnuZq0BDdP2VtGUUXjngIERw//2LN+eNPQtANloeyq601fTyMn51HSy2cby8D6aI5v1rX+/tO8H1wl+rRWLfHkIKeUvfRzjIc8nR0TQLB5qXkA8oHyVEgeF+M0VQYVW5pBlt8PUk0i1AFzUXZ5LdCZVwyWK2DVuovQ="
  file: MediaModule.zip
  on:
    tags: true
    repo: cmfcmf/MediaModule
