title: Media Module Docs
email: hi@christianflach.de
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Zikula Media Module.
url: "http://christianflach.de/MediaModule"
baseurl: "/MediaModule"
repository: "cmfcmf/MediaModule"

markdown: kramdown
highlighter: rouge

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
